import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const words = [
    { toki_pona: "a", english: "ah! ha! (emotion/confirmation)" },
    { toki_pona: "akesi", english: "reptile, amphibian" },
    { toki_pona: "ala", english: "no, not, zero" },
    { toki_pona: "alasa", english: "to hunt, gather, seek" },
    { toki_pona: "ale", english: "all, everything, 100" },
    { toki_pona: "ali", english: "all, everything, 100" },
    { toki_pona: "anpa", english: "low, lower, humble" },
    { toki_pona: "ante", english: "different, other, change" },
    { toki_pona: "anu", english: "or (choice question)" },
    { toki_pona: "awen", english: "to keep, endure, remain" },
    { toki_pona: "e", english: "(object marker)" },
    { toki_pona: "en", english: "and (joining subjects)" },
    { toki_pona: "esun", english: "market, trade, shop" },
    { toki_pona: "ijo", english: "thing, something, object" },
    { toki_pona: "ike", english: "bad, negative, undesirable" },
    { toki_pona: "ilo", english: "tool, device, machine" },
    { toki_pona: "insa", english: "inside, center, content" },
    { toki_pona: "jaki", english: "dirty, disgusting, unclean" },
    { toki_pona: "jan", english: "person, people, human" },
    { toki_pona: "jelo", english: "yellow, light green" },
    { toki_pona: "jo", english: "to have, own, possess" },
    { toki_pona: "kala", english: "fish, aquatic animal" },
    { toki_pona: "kalama", english: "sound, noise, voice" },
    { toki_pona: "kama", english: "to come, become, arrive" },
    { toki_pona: "kasi", english: "plant, vegetation, leaf" },
    { toki_pona: "ken", english: "can, able, possible" },
    { toki_pona: "kepeken", english: "to use, with, by means of" },
    { toki_pona: "kili", english: "fruit, vegetable, mushroom" },
    { toki_pona: "kin", english: "also, indeed, even" },
    { toki_pona: "kipisi", english: "cut, divide, split" },
    { toki_pona: "kiwen", english: "hard thing, metal, rock" },
    { toki_pona: "ko", english: "semi-solid, clay, paste" },
    { toki_pona: "kon", english: "air, spirit, essence" },
    { toki_pona: "kule", english: "color, hue, pigment" },
    { toki_pona: "kulupu", english: "group, community, society" },
    { toki_pona: "kute", english: "ear, to hear, to listen" },
    { toki_pona: "la", english: "(context marker)" },
    { toki_pona: "lape", english: "sleep, rest" },
    { toki_pona: "laso", english: "blue, green" },
    { toki_pona: "lawa", english: "head, leader, control" },
    { toki_pona: "len", english: "cloth, clothing, fabric" },
    { toki_pona: "lete", english: "cold, cool, unheated" },
    { toki_pona: "li", english: "(verb separator)" },
    { toki_pona: "lili", english: "small, little, few" },
    { toki_pona: "linja", english: "line, thread, cord" },
    { toki_pona: "lipu", english: "paper, document, book" },
    { toki_pona: "loje", english: "red, reddish" },
    { toki_pona: "lon", english: "true, real, to be at" },
    { toki_pona: "luka", english: "hand, arm, five" },
    { toki_pona: "lukin", english: "eye, to see, look" },
    { toki_pona: "lupa", english: "door, hole, opening" },
    { toki_pona: "ma", english: "land, earth, country" },
    { toki_pona: "mama", english: "parent, ancestor" },
    { toki_pona: "mani", english: "money, currency, wealth" },
    { toki_pona: "meli", english: "woman, female, wife" },
    { toki_pona: "mi", english: "I, me, we" },
    { toki_pona: "mije", english: "man, male, husband" },
    { toki_pona: "moku", english: "food, eat, drink" },
    { toki_pona: "moli", english: "dead, to die, death" },
    { toki_pona: "monsi", english: "back, rear, behind" },
    { toki_pona: "mu", english: "animal noise, meow, woof" },
    { toki_pona: "mun", english: "moon, star, night sky" },
    { toki_pona: "musi", english: "fun, game, play" },
    { toki_pona: "mute", english: "many, much, very" },
    { toki_pona: "namako", english: "extra, seasoning, spice" },
    { toki_pona: "nanpa", english: "number, count, rank" },
    { toki_pona: "nasa", english: "strange, foolish, weird" },
    { toki_pona: "nasin", english: "way, path, method" },
    { toki_pona: "nena", english: "bump, nose, hill" },
    { toki_pona: "ni", english: "this, that" },
    { toki_pona: "nimi", english: "name, word" },
    { toki_pona: "noka", english: "foot, leg, bottom" },
    { toki_pona: "o", english: "(vocative, imperative marker)" },
    { toki_pona: "olin", english: "love, care for" },
    { toki_pona: "ona", english: "he, she, they" },
    { toki_pona: "open", english: "to open, begin, start" },
    { toki_pona: "pakala", english: "mistake, damage, break" },
    { toki_pona: "pali", english: "to do, make, work" },
    { toki_pona: "palisa", english: "stick, rod, branch" },
    { toki_pona: "pan", english: "bread, grain, pasta" },
    { toki_pona: "pilin", english: "feeling, emotion, touch" },
    { toki_pona: "pimeja", english: "black, dark" },
    { toki_pona: "pini", english: "end, finish, stop" },
    { toki_pona: "poka", english: "side, beside, near" },
    { toki_pona: "poki", english: "container, box, cup" },
    { toki_pona: "pona", english: "good, positive, simple" },
    { toki_pona: "sama", english: "same, similar, like" },
    { toki_pona: "sewi", english: "high, superior, divine" },
    { toki_pona: "sina", english: "you" },
    { toki_pona: "suno", english: "sun, light" },
  ];

  res.status(200).json(words);
}
